In [15]:
from PIL import Image
from torchvision import transforms, models
from model.model import Model
import matplotlib.pyplot as plt

im = Image.open('images/cracow.tif')

In [16]:
import numpy as np
import torch
nim = np.array(im)
nim.shape

(4096, 5120, 3)

In [17]:
images = [im.crop((0 + 224*i, 0 + 224*j, 224 + 224*i, 224 + 224*j)) for i in range(10) for j in range(10)]
images[9].show()

In [18]:
transforms = transforms.Compose([            
    transforms.Resize((224, 224), interpolation=Image.NEAREST),
    transforms.ToTensor(),
#     transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
])


In [28]:
image = images[99]

In [48]:
model = Model()
model.load_state_dict(torch.load('model/state_dict.pth', map_location=torch.device('cpu')))
model.eval()

Using cache found in /home/witek/.cache/torch/hub/pytorch_vision_v0.10.0


Model(
  (base): ResNet(
    (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
    (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (relu): ReLU(inplace=True)
    (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
    (layer1): Sequential(
      (0): BasicBlock(
        (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu): ReLU(inplace=True)
        (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
      (1): BasicBlock(
        (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_

In [56]:
preds = [model(transforms(image).unsqueeze(0)) for image in images[:10]]
preds

[tensor([[0.0480]], grad_fn=<SigmoidBackward0>),
 tensor([[0.7318]], grad_fn=<SigmoidBackward0>),
 tensor([[0.0151]], grad_fn=<SigmoidBackward0>),
 tensor([[0.8364]], grad_fn=<SigmoidBackward0>),
 tensor([[0.0151]], grad_fn=<SigmoidBackward0>),
 tensor([[0.0007]], grad_fn=<SigmoidBackward0>),
 tensor([[0.7749]], grad_fn=<SigmoidBackward0>),
 tensor([[0.0229]], grad_fn=<SigmoidBackward0>),
 tensor([[0.0125]], grad_fn=<SigmoidBackward0>),
 tensor([[0.0067]], grad_fn=<SigmoidBackward0>)]

In [59]:
fig, ax = plt.subplots(10, 1)
for i, pred, image in zip(range(10), [round(pred.item()) for pred in preds], images[:10]):
    ax[i].imshow(image)
    ax[i].set_title(pred)

plt.show()

[0, 1, 0, 1, 0, 0, 1, 0, 0, 0]